### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by akauppi** [EmilTholin/svelte-spinner#5]
```
$ git clone git@github.com:EmilTholin/svelte-spinner.git
$ cd svelte-spinner/
$ npm install --save svelte-spinner
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "svelte-spinner" under a package
npm ERR! also called "svelte-spinner". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asko/.npm/_logs/2019-11-23T17_19_40_037Z-debug.log
```

MacOS with HomeBrew, 

```
$ npm --version
6.13.1
```

---

If I go with just `nom install --save`, I get this:

```
$ npm install --save
added 110 packages from 95 contributors, updated 10 packages and audited 917 packages in 2.904s
found 15 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

I'm trying to see the spinner in action (build and run). 

```
$ npm run build

> svelte-spinner@2.0.1 build /Users/asko/Sources/svelte-spinner
> rollup -c

src/index.svelte → dist/index.js...
created dist/index.js in 215ms

src/index.svelte → dist/index.mjs...
created dist/index.mjs in 33ms
```

..but what are the steps to get the `example` running, locally?

---

..found the `example/README.md` but unfortunately following it leads to loads of errors:

```
$ cd example
$ npm install

> fsevents@1.2.8 install /Users/asko/Sources/svelte-spinner/example/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.8/fse-v1.2.8-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.8 and node@13.1.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/asko/Sources/svelte-spinner/example/node_modules/fsevents
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.1.0/bin/node" "/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/asko/Sources/svelte-spinner/example/node_modules/fsevents
node-pre-gyp ERR! node -v v13.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/asko/Sources/svelte-spinner/example/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN example No repository field.
npm WARN example No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 3836 packages in 3.959s
found 61 vulnerabilities (1 low, 60 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by akauppi** [comment]
Solution:

```
$ cd example
$ npm outdated
$ npm update
```

```
$ npm start
...
```

Open `http://localhost:10001`:

><img width="252" alt="Näyttökuva 2019-11-23 kello 20 02 52" src="https://user-images.githubusercontent.com/1297734/69483157-963ab080-0e2c-11ea-8873-1c170edd0b61.png">

The `speed` setting does not seem to work (Safari); the rest does. :)   I'll post a PR with the dependency changes that worked for me.
